In [1]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4]+[5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [10]:
print(np.arange(1,6,dtype=float))    #to print the type of data
print(np.arange(1,6,2))   #start,end,interval

[1 3 5]


In [18]:
print(np.zeros((3,3),dtype=int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [24]:
print(np.full((3,3),5))

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [25]:
print(np.mean([1,2,3,4,5]))

3.0


In [28]:
print(np.sum([1,2,3,4,5]))

15


In [32]:
print(np.linspace(2,4,5,6))

[2.  2.5 3.  3.5 4. ]


In [33]:
print(np.median([1,2,3,4,5]))

3.0


In [34]:
print(np.std([1,2,3,4,5]))

1.4142135623730951


In [37]:
arr=np.array([1,2,3,4,5])
print(np.where(arr>2))

(array([2, 3, 4], dtype=int64),)


In [40]:
arr=np.array([1,2,3,4,5])
print(np.take(arr,[2,4]))

[3 5]


In [55]:
# print(np.repeat([[1,3],[4,5]],1,axis=1))
arr=np.array([[1,2],[4,5]])
print(np.repeat(arr,2,axis=1))

[[1 1 2 2]
 [4 4 5 5]]


In [63]:
a1=np.array([[1,2,3,4,5],[6,7,8,9,0]])
a2=np.array([[5,4,2,1,8],[4,5,2,6,1]])
# print(np.concatenate([a1,a2],axis=0))
print(np.concatenate([a1,a2]))

[[1 2 3 4 5 5 4 2 1 8]
 [6 7 8 9 0 4 5 2 6 1]]


In [64]:
a1=np.array([[1,2,3,4,5],[6,7,8,9,0]])
a2=np.array([[5,4,2,1,8],[4,5,2,6,1]])
# print(np.hstack([a1,a2]))
print(np.vstack([a1,a2]))

[[1 2 3 4 5]
 [6 7 8 9 0]
 [5 4 2 1 8]
 [4 5 2 6 1]]


In [69]:
arr=np.array([1,2,3,4,5])
print(arr**2)

[ 1  4  9 16 25]


In [77]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,0])
print(np.diff(a1))

[1 1 1 1]


In [81]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,0])
print(np.cross(a1,a2,axis=1))

AxisError: axisa: axis 1 is out of bounds for array of dimension 1